import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "wysiwyg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased relative`}>
        {children}
        <footer className="fixed w-full flex items-center bottom-0 h-10 z-20">
          <div className="w-full max-w-5xl m-auto">
            <small className="text-neutral-500">
              Made by  <a className="text-black underline" href="https://github.com/Jeff-Maina">Jeff</a>
            </small>
          </div>
        </footer>
      </body>
    </html>
  );
}
